---
title: "Hur väljer vi bra musik till våra kurser?"
format:
    revealjs:
        theme: [default, custom.scss]
        title-slide: false
        logo: ../img/wcsumea-logo-black.png
        footer: "Kursledarprogram WCS 2025-2026"
---

## Musik

Vad är målet?

Göra eleverna glada!

Musik kan hjälpa eller stjälpa.

Målgrupp?


## Musik

Grunderna:
- Tempo: 80-100 bpm
- Taktfast, 4/4, undvik förvirrande baktakt
- Tydlig downbeat (1, 3, 5, 7) och upbeat (2, 4, 6, 8)
- Undvik låtar med långa intro eller partier utan tydlig takt
- Variera genre och känsla
- Är explicita versioner okej?
- Observera hur dina elever reagerar på musiken. Är någon av låtarna för svår?


## Musik

Men:
- Undvik att välja "tråkig" musik (för mycket av samma)
- Om takten är svårare: räkna 1 2 3&4 5&6
- Hoppa över långa intron
- Vad är syftet med varje låt? Väljer du den för att den är "bra på papperet" eller av någon annan anledning?

Var försiktig:
- Känner du igen olämpliga/explicita texter?
- Låtar på andra språk?

Kom ihåg: Vi lär oss längs vägen. Det är okej att göra misstag.


## Övning

- Vilka låtar är bra för en nybörjarkurs? Varför (inte)?