project:
  type: website


# several branches can be specified here
branches:
  - branch: "release-2510"     # change this to the release branch
    output-dir: "2510"         # change this to year and month of the course instance

website:
  title: "Kursledarutbildning Steg 1"
  sidebar:
    style: "floating"
    background: "#F4F6F6"
    fontsize: 30px
    search: true
    contents: 
      - index.qmd 
      - schedule.qmd
      - course_material.qmd
      - step1_syllabus.qmd
      - links.qmd
  navbar:
    background: "#800080"
    logo: "img/wcsumea-logo.png"
  favicon: "img/wcsumea-logo.png"


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

execute:
  freeze: auto

