---
title: "Ramverk"
date: today
format:
  html: 
    toc: true
    theme: cosmo
  custom-pdfs-typst:
    keep-typ: true
format-links: false
course: "Kursledarutbildning Steg 1"
datetag: "Oktober 2025"
footer: "West Coast Swing Umeås kursledarprogram 2025-2026"
---

# Vad är ett ramverk?

Med ramverk menar vi små eller stora strukturer som kan användas för att planera/genomföra en kurs/kurstillfälle. Tanken med ett ramverk är att man använder en beprövad struktur, som i sin tur bygger på en pedagogisk princip.

[Ladda ner som PDF](frameworks.pdf){target="_blank"}


## Pedagogiska ramverk

#### Visa, Pröva, Instruera, Öva
Detta ramverk bygger på de pedagogiska principerna för hur personer lär. Inom dans har detta utvecklats till Visa, Pröva, Instruera, Öva. Ett ramverk som kan användas för att lära ut turer, se exemplet nedan med en Left side pass.  
 
- **Visa:** Instruktörerna börjar med att visa turen för kursdeltagarna. Kom ihåg att visa från både hållen. Räkna medan ni utför turen, både 1 2 3&4 5&6, samt gå gå trippelsteg trippelsteg. Nämn att en Left side pass ska följaren passera på förarens vänstra sida. Men inte mer information än så.

- **Pröva:** Låt deltagarna pröva turen själva, med intruktörerna som räknar in dem. Rotera ett par gånger så att alla får pröva. Målet är att följaren ska ta sig från en sida till den andra, och passera föraren på rätt sida.

- **Instruera:**  När deltagarna har fått in de ungefärliga riktningarna i kroppen kan ni som instruktörer gå igenom turen mer i detalj, och vilka tekniska detaljer som är viktiga.

- **Öva:** Nu får deltagarna tid att öva in turen med de extra detaljerna. Här kan ni också lägga till musik och räkna in deltagarna. Rotera ofta och ge ordentligt med tid att träna och ställa frågor.

#### Upplägg av kurstillfälle
Det finns flera sätt att strukturera ett kurstillfälle, men nedan följer ett simplet koncept som är en bra utgångspunkt:

- Repetition av föregående tillfälle
- Tekniskt koncept
- Tur som kräver det tekniska konceptet

Exempel:  

- Repetera föregående tillfälles tur: Left side pass
- Tekniskt koncept: snurrteknik (prep, spotting, korta steg)
- Tur som kräver det tekniska konceptet: Left side turn

#### Uppvärmning i grupp
Gå gå trippelsteg

#### Frågor och feedback

Fråga deltagarna efter varje genomgång om de har frågor. Om det är relevant för många i gruppen så gå igenom det i helklass. Är det en fråga som ni bedömmer bara är relevant för deltagaren som frågar, så gå till dem och ge dem feedback så fort ni får möjlighet.

Monitorera gruppen när de tränar, ser ni något som bör tas i helgrupp så säg vad ni såg, och hur ni vill att det ska se ut i stället. Försök att inte lägga någon värdering bakom det ni såg, säg till exempel inte att det såg dåligt ut, utan snarare att det är saker som saknas, och varför något är viktigt att göra.

#### Feedback mellan kursdeltagare
Frågan om feedback till sina kurskamrater är alltid känslig, men generellt är det bra att uppmana sina deltagare att INTE ge oombedd feedback till sin partner. Man kan själv be om feedback, till exempel fråga sin partner hur det känns när man själv gör turen, men har de frågor eller funderingar om de gör rätt är de bättre att de frågar kursledarna. Var tydig med detta i början av kursen, samt påminn dem de första gångerna om detta.

## Strukturramverk

#### Rotation och placering

- Börja alla turer med alla förare med ansiktet åt samma håll, det kommer underlätta för er som lärare att se om det är några problem med en tur
- Rotera följare motsols (eller medsols, de flesta roterar dock motsols)
- Placera ut extra följare jämnt så att det inte blir 2 ensamma följare på rad
- Säg "high five och rotera" vid varje rotation, det går deltagarna en chans att ha en mini-interaktion med varandra
- Rotera efter deltagarna har fått prova en sak 1-2 gånger med sin partner. Har ni extra följare så måste de få testa allt i minst 2 rotationer så alla får chans att testa. 

#### Räkning och takning

- Börja på "fel fot" för att lägga över vikten på 8 vid inräkning. Förklara varför ni gör detta
- Räkna in 5,6,7,8. Försök börja inräkningen så det timar med musikens 5,6,7,8
- Växla mellan att ibland räkna turer med siffror och ibland med gå gå trippelsteg
- Annonsera nästkommande tur på sista 5&6 i en tur så förarna har en chans att förbereda sig om ni har en given sekvens ni vill att de gör. Till exempel: 1 2 3&4 under arm

#### Lärarledd eller fri övning

Nedan följer olika sätt att ge sina kursdeltagare en struktur för att träna turer. När en tur först lärs ut så passar det lärarledda sättet. Vartefter gruppen förstår turen bättre och bättre kan man gå nedåt i listan, och avsluta med att låta paret dansa själv utan guidning.

**Lärarledd:** Läraren räknar in och hela gruppen gör turen tillsammans.

**Lärarledd start:** Läraren räknar in och hela gruppen gör turen tillsammans. Efter det fortsätter gruppen dansa, och förarna för turen själva, uppblandat med grundsteg.

**Halvfri:** Föraren får 2 turer att alternera mellan, men väljer själv vilken tur som förs. Räknas oftast in av kursledaren.

**Fritt:** Föraren väljer fritt vilka turer som dansas. Kursledaren kan dock instruerera att fokusera på en specifik tur. 


## Att inkludera?

- Enkel taktfast musik
- Diskutera med sin partner
- 7 truths of WCS