---
title: "Kursplanering Steg 1"
format:
  html: 
    toc: true
    theme: cosmo
  pdf: 
    latex-engine: xelatex
    documentclass: scrreprt
---


## Kurslängd

Följande kursplanering är anpassad till en veckokurs som är 1 timme gånger 8 tillfällen. Vid längre/kortare kurser, samt helgkurser, kan innehållet behöva anpassas.

[Ladda ner kursplanering som PDF](step1_syllabus.pdf){target="_blank"}

## Mål

Målet med en nybörjarkurs är att eleverna ska ha roligt, och vilja fortsätta dansa.

## Lärandemål

- Dansa grundturerna
- Starta på en downbeat
- Grundläggande frame
- Stretch
- Leka till musiken

## Turer

Följande turer passar att lära ut på en Nybörjarkurs. Beroende på antal gånger, samt hur gruppen är, kan detta behöva justeras något.

| Left side      | Middle       | Right side |
|----------------|--------------|------------|
| Left side pass | Sugar push   | Under arm  |
| Left side turn | Sugar tuck   | Whip       |
| Free spin      | Starter step |            |


## Tekniska koncept

Följande tekniska koncept är lämpliga att ta upp på en nybörjarkurs.

|             |                 | 
|-------------|-----------------|
| Frame       | Håll bak axlarna, engagera ryggen. Avslappnad biceps |
| Stretch     | Simplifierad: rulla ner långsamt på 6, release kommer från att höger (för följaren) häl lyfts från golvet |
| Connection? |  |
| Snurrteknik | Spotting, prep, korta steg |

: {tbl-colwidths="[25,75]"}


## Kursplanering

::: {.callout-warning icon=false}

## 
Se till att läsa de pedagogiska ramverken som medföljer denna kursplanering, då de inte alltid kommer nämnas explicit i texten, utan alltid ska användas.

:::

### Tillfälle 1

#### Introduktion (~5 min)

Börja alltid med att introducera er själva och hälsa alla välkomna. Praktisk information såsom nödutgångar, eventuella avbrott i kursen, etc, tas upp innan ni kör igång och dansar. Fråga gärna vilka som testat West Coast Swing tidigare, och berätta kort att dansen har sitt ursprung i Lindy Hop.

#### Grundstegen och förning (~15 min)

Starta med att berätta att WCS inte har ett grundsteg på samma sätt som t ex. salsa eller bugg, utan att vi snarare använder ett par olika grundturer, eller en grundrytm när vi dansar.

- **Gå gå trippelsteg:** Ställ deltagarna i en cirkel med ansiktet in mot mitten. Förarna börjar på vänster, och följarna på höger. En i lärarparet demonstrerar förarstegen och den andra följarstegen. Låt deltagarna stå själva och gå på stället och följa rytmen som ni demonstrerar. Välj en långsam låt med väldigt tydlig rytm för att träna till musik, ungefär 70-80 bpm första gången. Nästa steg är att låta deltagarna röra sig runt i rummet i samma rytm, både framåt och bakåt.

- **Handfattning och kroppsförning:** När alla fått in grundrytmen är det dags för deltagarna att hitta en partner och testa tillsammans. Förklara för deltagarna att i WCS kommer förningen från att föraren och följaren är i stretch (ytterläge) och när föraren rör sig bakåt kommer följaren att följa med, inget extra drag behövs. Demonstrera "tvåfingerkroken" där föraren lägger fram händerna, och följaren lägger händerna ovanpå. Målet är att få kroken så nära in i knogleden som möjligt. När de fattat varandras händer så instruera dem att slappna av i armarna, samtidigt som de håller axlarna på plats (detta för att skydda axlarna), och backa med små korta steg tills de börjar känna connection. Härifrån tar föraren ett steg bakåt, vilket får följaren att följa med. Se till att göra high five och rotera följarna så alla får prova. Det här är grundförningen som vi kommer använda i grundkursen. Allt detta bör förklaras så förenklat som möjligt, och inte ta mer än 5 minuter, då det kommer repeteras kommande tillfällen.

#### Left side pass (~20 min)

Använd VPIÖ för att lära ut (gäller alla turer) 

- Börja med att demonstrera turen från båda hållen
- Låt deltagarna testa turen, se till att rotera ett par gånger. Målet här är att följaren ska ta sig från en sida till nästa, och passera på förarens vänstra sida.
- Ge en mer detaljerad instruktion till turen.
  - Börja alltid med tvåfingerkroken och att backa ut i connection
  - Föraren går rakt bakåt på 1an, och kliver sedan ur spår
  - Både förare och följare måste vara avslappnade i armarna
  - Följaren kommer att gå rakt fram tills hen känner att connection får hen att rotera upp mot föraren igen.
  - Följaren är huvudsakligen ansvarig för att gå till ändläget och bygga upp stretch
- Låt deltagarna testa, både med er som räknar turen, och till slut med musik
- Monitorera gruppen för att se vad för problem som många har, och ta upp dessa saker i helgrupp, och visa hur det ska utföras
- Se till att deltagarna får många möjligheter att testa till musik

#### Under arm (~20 min)
- Börja med att demonstrera turen från båda hållen
- Låt deltagarna testa turen, se till att rotera ett par gånger. Målet här är att följaren ska ta sig från en sida till nästa, och passera på förarens högra sida.
- Ge en mer detaljerad instruktion till turen.
  - Börja alltid med tvåfingerkroken och att backa ut i connection
  - Säg åt förarna att titta på klockan, det kommer få dem att vända upp handen rätt så att följaren kan passera under
  - Både föraren och följaren måste vara avslappnade i armarna, annars kommer följaren att backa ut igen och inte gå under 
  - Följare ska rotera över sin vänstra axel
- Låt deltagarna testa, både med er som räknar turen, och till slut med musik
- Monitorera gruppen för att se vad för problem som många har, och ta upp dessa saker i helgrupp, och visa hur det ska utföras
- Se till att deltagarna får många möjligheter att testa till musik
- Låt deltagarna växla mellan left side pass och under arm, där förarna väljer vilken tur som kommer
  

::: {.callout-warning icon=false}

## 
Upplägget i efterföljande tillfällen är detsamma som ovan, men i texten kommer vi endast fokusera på de unika detaljerna för varje tur och koncept

:::

### Tillfälle 2

#### Repetition (~25 min)
Börja med att fråga om det var några som missade förra tillfället. Om så, ge lite extra stöd till dessa under repetitionen. Repetitionen ska i princip gå igenom samma saker som under förra lektionen, men under kortare tid.

- Repetera gå-gå-trippelsteg
- Repetera handfattning och connection
- Repetera Left side pass
- Repetera Under arm

#### Musikalitet i Under arm (~15 min)
Förklara att WCS är en dans där vi använder mycket musikalitet och kommunikation mellan förare och följare. De kommer få lära sig en enkel variation som följaren kan ta initiativ till.

- Följaren indikerar redan på 2& att hon vill göra något, genom att ge lite mer connection
- Visa några enkla varianter som följaren kan göra för att förlänga 3&4 med 2-4 taktslag
- Föraren väntar in följaren, eller följer med hen om det behövs. Med väntar menar vi att föraren tar steg på stället för att hålla takten.
- Följaren ansvarar för att avsluta turen korrekt
- Se till att rotera ofta och spela olika typer av musik så de får testa

#### Sugar push (~20 min)
Börja med kort stretch-compression övning där föraren och följaren står mot varandra, och växlar mellan stretch och compression genom att endast flytta vikten.

- Demonstrera en Sugar push och låt deltagarna testa. 
- Ge en mer detaljerad instruktion till turen.
  - Compression: följaren går till ändläget, och väntar där på att föraren för tillbaka hen
  - Föraren absorberar normalt mest av compressionen, men följaren kan också absorbera om nödvändigt
  - Viktigt att föraren inte pushar ut följaren med armarna, utan använder kroppen för att föra ut från compressionen
- Låt deltagarna träna på turen, och lägg även in de andra turerna de redan kan 


### Tillfälle 3

#### Repetition (~20 min)
Repetition av Sugar push och musikalitet i Under arm. Var uppmärksam på de som ej var med på föregående tillfälle om de behöver extra hjälp. Lägg gärna in Left side pass och Under arm mellan turerna så att du kan se om det är något där som måste repeteras.

#### Snurrteknik (~10 min)
Då nästa tur är Left side turn så bör kursledarna gå igenom en förenklad version av snurrteknik. 

Tekniken behövs främst för följarna, men även förarna har nytta av dessa övningar:

- Spotting: låt deltagaren fokusera blicken på en punkt rakt fram. Låt dem sakta rotera på stället tills de måste vrida huvudet för att åter kunna fokusera blicken på samma punkt
- Prep: snurra ett varv där prep från överkroppen används
- Små steg: Samma snurr som ovan där de också ska tänka på små steg i snurren, för att hålla balansen bättre

#### Left side turn (~20 min)

Ge en mer detaljerad instruktion till turen:

- Föraren steg är detsamma som i en vanlig Left side turn
- Prep på 1 och 2. Obs! Prepen på 1 är väldigt liten och är mest för att indikera för följaren att det kommer en annan prep. Prep på 2 ska föraren sätta handen något utanför förningslinjen
- Följaren håller tillbaka lite på 2 innan viktförflyttningen kommer
- Viktigt: följaren tar ner handen efter snurren, inte föraren. Detta för att undvika att föraren rycker ner följarens arm och det blir risk för skador
- När deltagarna tränar turen, säg till att de lägger till några andra turer emellan Left side turn, då ovana följare lätt kan bli yra av för mycket snurrande.

#### Fri dans (~10 min)

De sista 10 minuterna kan med fördel användas för att låta deltagarna dansa fritt med de turer de lärt sig hittills. Spela musik och rotera ofta. Ser du att deltagarna har problem att starta själva, räkna in efter varje rotation.

### Tillfälle 4

#### Repetition (~20 min)
Kort repetition av Sugar push + repetition av snurrteknik och Left side turn.


#### Sugar tuck (~20 min)
Ge en mer detaljerad instruktion till turen:

- Föraren steg är detsamma som i en vanlig Sugar push
- Föraren placerar vänster hand upp, ungefär i höjd med följarens huvud
- Följaren måste fortfarande gå in i compressionen liknande som i Sugar push
- Viktigt: följaren tar ner handen efter rotationen, inte föraren. Detta för att undvika att föraren rycker ner följarens arm och det blir risk för skador
- Efter turen kommer handfattningen att vara "upp och ned", fråga deltagarna vilken tur de kan använda för att fixa till detta (Under arm)
- Låt deltagarna variera mellan vanlig Sugar push och Sugar tuck, för att tydliggöra att känslan och stegen är väldigt lika

#### Följarstyling i Sugar tuck (~20 min)
Detta är också en styling som följare kan ta initiati till och förlänga en tur.

- För att tydliggöra att följaren vill göra något, instruera dem att lägga vänsterhanden på förarens vänsterhand på &4, för att visa att de vill ha utrymme
- Visa en enkel förlängning av turen för följare (t ex. lägg till 2 gåsteg)
- Följaren ansvarar för att gå ut i stretch och avsluta turen

### Tillfälle 5

#### Repetition (~20 min)
Kort repetition av Sugar push och Sugar tuck tillsammans, för att demonstrera på likheterna och skillnaderna däremellan. Repetera följarvariationen från 4an, lägg gärna in en annan enkel variation de kan göra.

#### Connectionövning (~15 min)

Nu när deltagarna har provat på några turer, passar det att lägga in en teknikövning med mer fokus på connection. Både hand i hand och connection bak i ryggen. Viktiga detaljer att ta upp:

- Connection på ryggen: handen ska vara vinklad, inga fingrar in i ryggen
- Handen direkt under följarens vänstra skulderblad
- Viktigt att följaren söker connection, dock utan att luta sig bakåt då de då blir tunga

#### Starter step med Left side pass (~25 min)
Förklara att när man börjar dansen börjar man oftast i sluten position (de kan redan ha haft frågor om detta om de sett socialdans). Då starter step är en av de mer "kontroversiella" turerna i hur den ska utföras, låter vi er själva bestämma vilken variant ni lär ut. Försök dock vara konsekventa med andra kursledare inom er förening, och var medveten om de olika varianterna:

- **Tap, step:** Tap på 1 och steg på 2, ankarsteg på 3&4
- **Step, tap:** Steg på 1 och tap på 2, ankarsteg på 3&4
- **Trippelsteg:** Trippelsteg på 1&2, ankarsteg på 3&4

Alla varianter bör dock börja med att paret hittar takten först, tap, step om ni lär ut varianten med tap, step eller trippelsteg, eller step tap om ni lär ut varianten med step, tap. Låt deltagarna få in rytmen ett tag med musik för att hitta känslan, innan ni börjar med starter step.

Då detta är första gången de testar sluten position är det en del punkter som är extra viktiga. Förutom de punkter som är listade för closed connection ovan så är även följande saker viktiga att nämna:

- Se till att förarens frame följer med i starter stepet, ibland lämnar förarna kvar följarna när de själva går åt sidan
- Förklara att förningen kommer från den hand som är närmast följarens center. Vilket betyder att förarens vänsterhand inte för alls

Då starter step utan en utgång blir lite tråkig att träna på, lägg till en Left side pass från sluten position till öppen. Principen här är densamma som för en vanlig Left side pass, men då föraren har connection i ryggen är det därifrån förningen kommer ifrån. Ha dem gärna släppa vänsterhanden helt för att träna på förning från handen på ryggen.


### Tillfälle 6

#### Repetition (~20 min)
Kort repetition av Starter step och connection.

#### Stretch och compression (~15 min)
Ge en mer detaljerad beskrivning av stretch och compression och hur det används i WCS. Låt deltagarna öva på att alltid gå till ändlägena och vänta på förning. Bra övningar:

- Endast gå, ej dans: Följarna går tills de får en redirect
- Dansövning: Förarna lägger in gå-gå steg mellan turerna, så att följarna måste vänta på förning. Lägg in gå-gå steg i compressionen i Sugar push 

#### Whip (~25 min)
Introducera deras första 8-taktstur genom att demonstrera rytmen och låta dem testa gå-gå trippelsteg gå-gå trippelsteg på stället. En Whip är en av de svårare turerna att behärska, och kommer kräva en del träning innan de får till den. Några viktiga punkter att tänka på i Whipen:

- Föraren öppnar upp sin fram något innan ettan, så att följaren får en naturlig "prep" innan steget, vilket får henne att rotera automatiskt
- Föraren bör fånga upp följarens rygg så snart som möjligt, för att kunna "släppa ut och dra in" på steg 3&4
- Följaren måste fortsätta momentum bakåt tills hen får en redirect
- På steg 4 ska följaren ha höger fot fram, men inte än ha lagt över vikten, vikten kommer på &et efteråt
- Förare ska inte heller ha lagt över vikten på 4an, utan viktförflyttningen sker på &et efteråt. Många förare är alldeles för snabba att lägga över vikten, och kan då inte längre föra ut följaren ordentligt
- Stanna på 4an ett par gånger för att inspektera positionerna som förare och följare har 
- Så fort handen connectar med ryggen så är det den förningspunkt som gäller, då den är närmare följarens center, den andra handen för ej ut, utan rotationen och förningen ut kommer från förarens rotation och frame
- Förare har en tendens att pusha ut följaren på 5&6 med sin vänsterarm. För att undervika detta kan deltagarna träna på att släppa den andra handen så fort de connectat i ryggen


### Tillfälle 7

#### Repetition (~25 min)
Repetition av Whip och connection. Ta gärna lite extra tid att repetera detta, då Whipen är ganska svår att få in, och deltagarna ofta har många frågor.

#### Handbyten och grundturer i olika handfattningar (~20 min)
Då deltagarna redan kan en hel del grundturer vid det här laget, passar det här att lägga in handbyten. Visa några enkla handbyten, till exempel i Under arm (höger i höger), Left side pass (höger i höger), och Sugar push (höger i vänster). Låt deltagarna själva testa på grundturerna i olika handfattningar först, för att sedan gå igenom om de har några tankar kring hur väl de olika turerna fungerar i olika handfattningar.

#### Freespin (~15 min)
Låt deltagarna göra en Sugar push med handbyte, så de hamnar höger i vänster. Viktiga punkter att tänka på i Freespin är:

- Förarens och följarens steg är desamma som i en vanlig Left side turn
- Föraren höjer inte armen för att signalera att följaren ska gå under, utan håller handen låg, för att sedan släppa efter preppen på 2

Många gånger är Freespin höger i vänster lättare att göra för deltagarna än en Left side turn, då både föraren och följaren får lite mer utrymme då handfattningen är annorlunda.

### Tillfälle 8

- Repetition av turer, antingen alla turer individuellt eller genom en slinga

### Slinga av alla turer

Nedan följer en variant av en slinga på 2x32 slag, som kan varieras utefter behov. Då de aldrig kommer att komma ihåg hela slingan är det viktigt att ni som kursledare hela tiden ropar ut vilken tur som kommer härnäst.

| Takt  | Tur     | Kommentar |
|-------|---------|-----------|
| 1-4   | Starter step |   |
| 5-10  | Left side pass |     |
| 11-16 | Under arm | Lägg gärna in följarstylingen på 3&4 |
| 17-22 | Sugar push | Miniphrase change, möjlighet till styling |
| 23-28 | Left side turn | |
| 29-32 | Start av Tuck turn | Phrase change kommer på 5an |
| 1-6   | Fortsätt Tuck turn | Förläng turen med 4 slag, följarstyling |
| 7-12  | Free spin | |
| 13-20 | Whip  | Miniphrase change, lägg eventuellt in en slide på 5an |
| 21-26 | Left side pass in i sluten | |
| 27-32 | Left side pass ut ur sluten | |
| Eventuellt ta nästa phrase change | |

